function rig_test()
%rig_test
%   Testing rig_test with Bpod-Gen2
global BpodSystem

Ack = LoadSerialMessages('PA1', ['L' 0],10); %close all LEDS on PA1

Ack = LoadSerialMessages('PA1', ['L' 1],11); %Yellow LED for MidR
Ack = LoadSerialMessages('PA1', ['L' 16],12); %blue LED for MidR

Ack = LoadSerialMessages('PA1', ['L' 2],21); %Yellow LED for TopR
Ack = LoadSerialMessages('PA1', ['L' 32],22); %blue LED for TopR

Ack = LoadSerialMessages('PA1', ['L' 4],31); %Yellow LED for TopL
Ack = LoadSerialMessages('PA1', ['L' 64],32); %blue LED for TopL

Ack = LoadSerialMessages('PA1', ['L' 8],41); %Yellow LED for MidL
Ack = LoadSerialMessages('PA1', ['L' 128],42); %blue LED for MidL


sma = NewStateMachine();

sma = AddState(sma, 'Name', 'WaitForPokePA1', ...
   'Timer', 0,...
   'StateChangeConditions', {'PA1_Port1In', 'InPokePA1'},...
   'OutputActions', {'PA1',11});

sma = AddState(sma, 'Name', 'InPokePA1', ...
   'Timer', 0,...
   'StateChangeConditions', {'PA1_Port1Out', 'WaitForPokePA2'},...
   'OutputActions', {'PA1',12});% turn on blue LED

sma = AddState(sma, 'Name', 'WaitForPokePA2', ...
   'Timer', 0,...
   'StateChangeConditions', {'PA1_Port2In', 'InPokePA2'},...
   'OutputActions', {'PA1',21});

sma = AddState(sma, 'Name', 'InPokePA2', ...
   'Timer', 0,...
   'StateChangeConditions', {'PA1_Port2Out', 'WaitForPoke1'},...
   'OutputActions', {'PA1',22});


sma = AddState(sma, 'Name', 'WaitForPoke1', ...
    'Timer', 0,...
    'StateChangeConditions', {'Port1In', 'InPoke1'},...
    'OutputActions', {'PWM1',255});

sma = AddState(sma, 'Name', 'InPoke1', ...
    'Timer', 0,...
    'StateChangeConditions', {'Port1Out', 'WaitForPoke2'},...
    'OutputActions', {'LED1',255});

sma = AddState(sma, 'Name', 'WaitForPoke2', ...
    'Timer', 0,...
    'StateChangeConditions', {'Port2In', 'InPoke2'},...
    'OutputActions', {'PWM2',255});

sma = AddState(sma, 'Name', 'InPoke2', ...
    'Timer', 0,...
    'StateChangeConditions', {'Port2Out', 'WaitForPokePA3'},...
    'OutputActions', {'LED2',255});

sma = AddState(sma, 'Name', 'WaitForPokePA3', ...
   'Timer', 0,...
   'StateChangeConditions', {'PA1_Port3In', 'InPokePA3'},...
   'OutputActions', {'PA1',31});

sma = AddState(sma, 'Name', 'InPokePA3', ...
   'Timer', 0,...
   'StateChangeConditions', {'PA1_Port3Out', 'WaitForPoke3'},...
   'OutputActions', {'PA1',32});

sma = AddState(sma, 'Name', 'WaitForPoke3', ...
    'Timer', 0,...
    'StateChangeConditions', {'Port3In', 'InPoke3'},...
    'OutputActions', {'PWM3',255});

sma = AddState(sma, 'Name', 'InPoke3', ...
    'Timer', 0,...
    'StateChangeConditions', {'Port3Out', 'WaitForPokePA4'},...
    'OutputActions', {'LED3',255});

sma = AddState(sma, 'Name', 'WaitForPokePA4', ...
   'Timer', 0,...
   'StateChangeConditions', {'PA1_Port4In', 'InPokePA4'},...
   'OutputActions', {'PA1',41});

sma = AddState(sma, 'Name', 'InPokePA4', ...
   'Timer', 0,...
   'StateChangeConditions', {'PA1_Port4Out', 'WaitForPoke4'},...
   'OutputActions', {'PA1',42});

sma = AddState(sma, 'Name', 'WaitForPoke4', ...
    'Timer', 0,...
    'StateChangeConditions', {'Port4In', 'InPoke4'},...
    'OutputActions', {'PWM3',255});

sma = AddState(sma, 'Name', 'InPoke4', ...
    'Timer', 0,...
    'StateChangeConditions', {'Port4Out', 'WaitForEndPoke'},...
    'OutputActions', {'LED4',255});

% end poke is port 2 (MidC)
sma = AddState(sma, 'Name', 'WaitForEndPoke', ...
    'Timer', 0,...
    'StateChangeConditions', {'Port2In', 'InEndPoke'},...
    'OutputActions', {'PWM2',255});

sma = AddState(sma, 'Name', 'InEndPoke', ...
    'Timer', 0,...
    'StateChangeConditions', {'Port2Out', 'exit'},...
    'OutputActions', {'LED2',255});

SendStateMatrix(sma);
RawEvents = RunStateMatrix;
Ack = ResetSerialMessages;

end

